//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "parse_errors")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub file_path: String,
    #[sea_orm(column_type = "Text")]
    pub error_message: String,
    pub line_number: Option<i32>,
    pub timestamp: DateTimeWithTimeZone,
    pub acknowledged: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
