//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::parse_errors::Entity as ParseErrors;
pub use super::processed_files::Entity as ProcessedFiles;
pub use super::settings::Entity as Settings;
pub use super::test_results::Entity as TestResults;
pub use super::watcher_lock::Entity as WatcherLock;
