//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::fg::Entity as Fg;
pub use super::report::Entity as Report;
pub use super::test::Entity as Test;
pub use super::user::Entity as User;
