//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "test")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub report_id: Option<i32>,
    pub fg_id: i32,
    pub test_type: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub frequency: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub voltage: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub minimum: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub maximum: Option<f64>,
    pub uo_m: String,
    pub primary_pins: Option<String>,
    pub secondary_pins: Option<String>,
    pub shorted_pins: Option<String>,
    pub description: Option<String>,
    pub added_by: Option<i32>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fg::Entity",
        from = "Column::FgId",
        to = "super::fg::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Fg,
    #[sea_orm(
        belongs_to = "super::report::Entity",
        from = "Column::ReportId",
        to = "super::report::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Report,
}

impl Related<super::fg::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fg.def()
    }
}

impl Related<super::report::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Report.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
