//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::manual_test_results::Entity as ManualTestResults;
pub use super::processed_files::Entity as ProcessedFiles;
pub use super::settings::Entity as Settings;
