//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "processed_files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub file_name: String,
    #[sea_orm(unique)]
    pub file_path: String,
    pub processed_at: DateTimeWithTimeZone,
    pub record_count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
